### PR TITLE
fix for shadow dom

### PR DESCRIPTION
**Pull request by Belsi**
Hi Marco,
I fix your DnD to work with polymer. It's only in added Document in which events happens.
Feel free about pull / rewrite / drop this ;)

Br,
František Belšán

### CODE REVIEW

**Comment by marcojakob** [comment]
Thanks for the pull request. I've chosen a bit a different approach. Could you verify that this works: https://github.com/marcojakob/dart-dnd/issues/3

**Comment by Belsi** [comment]
Hi Marco,

Sorry about long silence.
Your fix is working too, but for me is not as modular solution as can be. I have whole app structured as polymers and now i have to put for every parent "dnd-retarget".

And in this solution (even in the one from me) is some problem with items with childs elements. I have code like this:

.item-content{
  width: 200px;
  height: 50px;
}
.handler{
  float:left;
  background-color:#CCC;
  width: 50px;
  height: 50px;
}


<div class="item item2">
  <div class="item-content">
    <div class="handler"></div>
       Item 2
  </div>
</div> 

And the handler works great, but when i go to .item-content, hovered element lose overClass.

Br,
František Belšán.

**Comment by marcojakob** [comment]
I agree that this is not an optimal solution to add that many `dnd-retarget` attributes. The reason is that  if we don't have this, the performance might suffer a lot: When dragging somthing we would need to check every child polymer element if it is a dropzone via recursive `elementFromPoint(...)` calls. By declaring `dnd-retarget` the library knows that it can stop when the attribute is not present on an element.

If you have a better idea I would be glad to change it.

Your other problem: There seems to be a bug in Dartium. Can you try in another browser with the generated JS version?

**Comment by Belsi** [comment]
I think solution could be something like the example i send you first time. To set the Document in which events are listen. Is that a bad solution according to you?

About second problem u are right, thx.

**Comment by marcojakob** [comment]
I might be wrong about your solution, but I think it will only work when your dragging inside one shadow dom node and only its immediate children. As soon as you have nested polymer web components you will also have nested shadow roots.

Imagine the following situation: 

```
<element-a>
  <element-b>
    <element-c>
    </element-c>
  </element-b>
</element-a>
```
The dropzone is nested in other web components. If you drag something from the outside over `<element-c>` events will not pass through to the shadow dom of that element even if you set listeners on the shadow dom of `<element-c>`.

**Comment by Belsi** [comment]
Yeah, u r right. 
I don't know how to solve this. Maybe some component like dnd-wrapper, which could handle dnd-retargetting on childs, but that isn't excellent solution too. :-/

**Comment by marcojakob** [comment]
Such a wrapper would need to be the outermost polymer element and would then need to retarget to all its children.

I think it should be not such a big task to add the `dnd-retarget` attribute. This could also be done programmatically. You could take the dropzone and travel up all its parents and add it to each parent.

**Pull request merged**
